[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='lambda-pr'
folder='input'

[db]
host='crsu08qay9nu.ap-south-1.rds.amazonaws.com'
port=3306
database='lambda-pr'
schema='superstore'




    

    